import type { Metadata } from "next";
import { Faustina, Fauna_One, Lato, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const faustina = Faustina({ subsets: ["latin"], weight: ["400","500"], variable: "--font-faustina" });
const faunaOne = Fauna_One({ subsets: ["latin"], weight: "400", variable: "--font-fauna-one" });
const lato = Lato({ subsets: ["latin"], weight: ["400","700"], variable: "--font-lato" });
const inter = Inter({ subsets: ["latin"], weight: ["300","400","500"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${faustina.variable} ${faunaOne.variable} ${lato.variable} ${inter.variable} antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
